// Farm Craft — mock catalog data.
// This file stands in for a future `GET /products` API response.
// Shape mirrors the documented data model (see /docs/data-model.md):
// Product { id, name, slug, category, description, images, price, discountPrice,
//           stock, stockStatus, specifications, features, applications }

export const CATEGORIES = [
  { id: 'transferring',  name: 'Grain Transferring',        icon: 'move-horizontal', img: 'assets/products/pipe-coil-1.jpeg' },
  { id: 'collecting',    name: 'Grain Collecting',           icon: 'circle-dot',      img: 'assets/products/collector-field.jpeg' },
  { id: 'bagging',       name: 'Grain Bagging',              icon: 'package',         img: 'assets/products/collector-bags.jpeg' },
  { id: 'handling',      name: 'Grain Handling Equipment',   icon: 'warehouse',       img: 'assets/products/pipe-frame.jpeg' },
  { id: 'machinery',     name: 'Agricultural Machinery',     icon: 'tractor',         img: 'assets/products/collector-diagram.jpeg' },
  { id: 'accessories',   name: 'Pipes & Accessories',        icon: 'cable',           img: 'assets/products/pipe-mounted-2.jpeg' },
];

export const HIGHLIGHTS = [
  { icon: 'gauge',        value: '18 Tons/Hour',  label: 'High Transfer Capacity' },
  { icon: 'ruler',        value: '30–500 Feet',   label: 'Pipe Length Options' },
  { icon: 'move-vertical',value: '20 Feet',        label: 'Transfer Height' },
  { icon: 'zap',          value: '5 HP–16 HP',     label: 'Motor Options' },
  { icon: 'package-check',value: '90 Bags/Hour',   label: 'Bagging Capacity' },
];

export const PRODUCTS = [
  {
    id: 'p1',
    name: 'Grain Transferring Pipe',
    slug: 'grain-transferring-pipe',
    category: 'transferring',
    description: 'Heavy-duty grain transferring solution designed for efficient transfer of grains and powders across long distances.',
    images: ['assets/products/pipe-coil-2.jpeg', 'assets/products/pipe-mounted-1.jpeg', 'assets/products/pipe-studio-1.jpeg'],
    price: null,
    discountPrice: null,
    stock: 24,
    stockStatus: 'In Stock',
    specifications: [
      { label: 'Length', value: '30 ft – 500 ft' },
      { label: 'Height', value: '20 ft' },
      { label: 'Capacity', value: '18 tons/hour' },
      { label: 'Screw', value: 'SS (Stainless Steel)' },
      { label: 'Pipe', value: 'HDPE' },
      { label: 'Motor', value: '5 HP – 16 HP' },
    ],
    features: [
      'Heavy-duty industrial design',
      'Long-distance grain transfer',
      'Suitable for all types of grains',
      'Suitable for powders',
      'Multiple length configurations',
      'Multiple motor configurations',
      'Built for agricultural and industrial use',
    ],
    applications: ['Rice', 'Wheat', 'Corn', 'Soybean', 'Feed', 'Powders'],
    rating: 4.7,
    reviews: 38,
  },
  {
    id: 'p2',
    name: 'Grain Collecting & Bagging Machine',
    slug: 'grain-collecting-bagging-machine',
    category: 'bagging',
    description: 'A powerful, portable machine designed for collecting grains and powders from the ground and efficiently filling bags.',
    images: ['assets/products/collector-bags.jpeg', 'assets/products/collector-field.jpeg', 'assets/products/collector-diagram.jpeg'],
    price: null,
    discountPrice: null,
    stock: 15,
    stockStatus: 'In Stock',
    specifications: [
      { label: 'Motor', value: '5 HP single phase' },
      { label: 'Capacity', value: '90 bags/hour' },
      { label: 'Used For', value: 'Collecting grains & powders into bags' },
      { label: 'Suitable For', value: 'All kinds of grains and powders' },
    ],
    features: [
      '5 HP single-phase motor',
      '90 bags/hour capacity',
      'Efficient ground-level grain collection',
      'Direct bag-filling support',
      'Suitable for various grains',
      'Suitable for powders',
      'Designed for agricultural operations',
    ],
    applications: ['Rice', 'Corn', 'Wheat', 'Soybean', 'Side crops', 'Feed'],
    rating: 4.8,
    reviews: 52,
  },
  {
    id: 'p3',
    name: 'Portable Grain Transfer Machine',
    slug: 'portable-grain-transfer-machine',
    category: 'transferring',
    description: 'A compact, wheeled grain transfer unit built for quick relocation between trucks, stores and threshing yards.',
    images: ['assets/products/pipe-mounted-2.jpeg', 'assets/products/pipe-frame.jpeg', 'assets/products/pipe-coil-1.jpeg'],
    price: null,
    discountPrice: null,
    stock: 19,
    stockStatus: 'In Stock',
    specifications: [
      { label: 'Motor', value: '5 HP – 16 HP' },
      { label: 'Capacity', value: 'Up to 18 tons/hour (config. dependent)' },
      { label: 'Mobility', value: 'Wheeled frame' },
      { label: 'Pipe', value: 'HDPE, coilable' },
    ],
    features: [
      'Wheeled frame for fast repositioning',
      'Coilable pipe for easy storage',
      'Configurable motor output',
      'Low-maintenance build',
    ],
    applications: ['Rice', 'Corn', 'Wheat', 'Bean', 'Soybean', 'Feed', 'Other grains and powders'],
    rating: 4.6,
    reviews: 21,
  },
  {
    id: 'p4',
    name: 'Track-Mounted Grain Collector',
    slug: 'track-mounted-grain-collector',
    category: 'collecting',
    description: 'Rubber track-mounted collector that moves smoothly across grain heaps, feeding an inclined elevator into waiting bags.',
    images: ['assets/products/collector-field.jpeg', 'assets/products/collector-bags.jpeg', 'assets/products/collector-diagram.jpeg'],
    price: null,
    discountPrice: null,
    stock: 9,
    stockStatus: 'Low Stock',
    specifications: [
      { label: 'Drive', value: 'Petrol engine, track-mounted' },
      { label: 'Elevator Angle', value: 'Adjustable incline' },
      { label: 'Capacity', value: 'Up to 90 bags/hour' },
      { label: 'Terrain', value: 'Loose grain heaps, threshing floors' },
    ],
    features: [
      'Rubber tracks for stable movement on grain',
      'Adjustable incline elevator',
      'Petrol-powered for off-grid use',
      'Reinforced intake auger',
    ],
    applications: ['Rice', 'Corn', 'Wheat', 'Side crops', 'Soybean'],
    rating: 4.5,
    reviews: 17,
  },
  {
    id: 'p5',
    name: 'Heavy Duty Grain Auger Conveyor',
    slug: 'heavy-duty-grain-auger-conveyor',
    category: 'handling',
    description: 'A robust auger conveyor for moving high volumes of grain between storage, transport and processing points.',
    images: ['assets/products/pipe-frame.jpeg', 'assets/products/pipe-coil-2.jpeg', 'assets/products/pipe-mounted-1.jpeg'],
    price: null,
    discountPrice: null,
    stock: 12,
    stockStatus: 'In Stock',
    specifications: [
      { label: 'Frame', value: 'Powder-coated steel' },
      { label: 'Capacity', value: '18 tons/hour' },
      { label: 'Motor', value: '5 HP – 16 HP' },
      { label: 'Mounting', value: 'Fixed frame with stabilizer legs' },
    ],
    features: [
      'Stabilizer legs for safe fixed operation',
      'Powder-coated frame resists corrosion',
      'High-volume continuous operation',
      'Compatible with multiple grain types',
    ],
    applications: ['Rice', 'Wheat', 'Corn', 'Feed'],
    rating: 4.6,
    reviews: 29,
  },
  {
    id: 'p6',
    name: 'Coilable HDPE Transfer Pipe (100ft)',
    slug: 'coilable-hdpe-transfer-pipe-100ft',
    category: 'accessories',
    description: 'A flexible, food-grade HDPE pipe section built to pair with any Farm Craft transfer motor unit.',
    images: ['assets/products/pipe-coil-1.jpeg', 'assets/products/pipe-studio-1.jpeg', 'assets/products/pipe-coil-2.jpeg'],
    price: null,
    discountPrice: null,
    stock: 40,
    stockStatus: 'In Stock',
    specifications: [
      { label: 'Length', value: '100 ft (custom lengths available)' },
      { label: 'Material', value: 'Food-grade HDPE' },
      { label: 'Diameter', value: 'Standard fit' },
      { label: 'Coil Weight', value: 'Light, one-person handling' },
    ],
    features: [
      'Food-grade material safe for grain contact',
      'Tight-coil storage',
      'Abrasion-resistant outer layer',
      'Compatible with standard Farm Craft motor heads',
    ],
    applications: ['Rice', 'Wheat', 'Corn', 'Soybean', 'Powders'],
    rating: 4.4,
    reviews: 11,
  },
  {
    id: 'p7',
    name: 'Compact Bench-Frame Transfer Unit',
    slug: 'compact-bench-frame-transfer-unit',
    category: 'machinery',
    description: 'A stationary, bench-frame mounted transfer unit suited to smaller stores and mill loading bays.',
    images: ['assets/products/pipe-frame.jpeg', 'assets/products/pipe-mounted-2.jpeg', 'assets/products/pipe-coil-2.jpeg'],
    price: null,
    discountPrice: null,
    stock: 7,
    stockStatus: 'Low Stock',
    specifications: [
      { label: 'Frame', value: 'Welded steel bench frame' },
      { label: 'Motor', value: '5 HP' },
      { label: 'Capacity', value: 'Up to 10 tons/hour' },
      { label: 'Footprint', value: 'Compact, fixed placement' },
    ],
    features: [
      'Small footprint for tight loading bays',
      'Simple single-point installation',
      'Low power draw',
    ],
    applications: ['Rice', 'Wheat', 'Feed'],
    rating: 4.3,
    reviews: 8,
  },
  {
    id: 'p8',
    name: 'Industrial Grain Handling System',
    slug: 'industrial-grain-handling-system',
    category: 'handling',
    description: 'A complete multi-stage system combining collection, transfer and bagging for high-throughput operations.',
    images: ['assets/products/collector-diagram.jpeg', 'assets/products/collector-field.jpeg', 'assets/products/pipe-mounted-1.jpeg'],
    price: null,
    discountPrice: null,
    stock: 4,
    stockStatus: 'Low Stock',
    specifications: [
      { label: 'Stages', value: 'Collect → Transfer → Bag' },
      { label: 'Combined Capacity', value: 'Up to 18 tons/hour' },
      { label: 'Motor Total', value: '16 HP+ (multi-unit)' },
      { label: 'Setup', value: 'Modular, site-configured' },
    ],
    features: [
      'End-to-end grain handling in one system',
      'Modular units configured to site layout',
      'Suited to mills and large agricultural businesses',
      'Reduced manual handling across stages',
    ],
    applications: ['Rice', 'Corn', 'Wheat', 'Soybean', 'Feed', 'Powders'],
    rating: 4.9,
    reviews: 14,
  },
  {
    id: 'p9',
    name: 'Grain Transfer Motor Head (16 HP)',
    slug: 'grain-transfer-motor-head-16hp',
    category: 'accessories',
    description: 'A high-output 16 HP motor head unit for maximum-capacity transfer runs and longer pipe lengths.',
    images: ['assets/products/pipe-studio-1.jpeg', 'assets/products/pipe-coil-1.jpeg', 'assets/products/pipe-frame.jpeg'],
    price: null,
    discountPrice: null,
    stock: 10,
    stockStatus: 'In Stock',
    specifications: [
      { label: 'Motor', value: '16 HP' },
      { label: 'Screw', value: 'SS (Stainless Steel)' },
      { label: 'Compatible Pipe', value: '30 ft – 500 ft HDPE' },
      { label: 'Phase', value: 'Three phase' },
    ],
    features: [
      'Maximum-capacity motor for long-distance runs',
      'Stainless steel screw for durability',
      'Compatible with the full Farm Craft pipe range',
    ],
    applications: ['Rice', 'Wheat', 'Corn', 'Soybean', 'Powders'],
    rating: 4.7,
    reviews: 19,
  },
  {
    id: 'p10',
    name: 'Single-Phase Bagging Attachment',
    slug: 'single-phase-bagging-attachment',
    category: 'bagging',
    description: 'A dedicated bag-filling attachment that pairs with Farm Craft collectors for consistent, fast bag loading.',
    images: ['assets/products/collector-bags.jpeg', 'assets/products/collector-diagram.jpeg', 'assets/products/collector-field.jpeg'],
    price: null,
    discountPrice: null,
    stock: 22,
    stockStatus: 'In Stock',
    specifications: [
      { label: 'Motor', value: '5 HP single phase' },
      { label: 'Capacity', value: '90 bags/hour' },
      { label: 'Bag Compatibility', value: 'Standard 50kg woven bags' },
    ],
    features: [
      'Consistent fill weight across bags',
      'Fast-swap bag mounting',
      'Pairs with any Farm Craft collector unit',
    ],
    applications: ['Rice', 'Corn', 'Wheat', 'Soybean', 'Feed'],
    rating: 4.5,
    reviews: 25,
  },
];

export function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug) || null;
}

export function getProductById(id) {
  return PRODUCTS.find(p => p.id === id) || null;
}

export function getCategoryName(id) {
  const c = CATEGORIES.find(c => c.id === id);
  return c ? c.name : id;
}

export const COMPANY = {
  name: 'Farm Craft',
  gstin: '37AQXPV3001H1ZG',
  logo: 'assets/logo.jpeg',
  email: 'contact@farmcraft.demo',
  phone: '+91 90000 00000',
  whatsapp: '919000000000', // digits only, country code first — used for wa.me links (demo placeholder)
  address: 'Farm Craft Works, Industrial Road, Andhra Pradesh, India',
  addressNote: 'Demo placeholder — actual company address to be confirmed.',
};

// Company services — mirrors a future `GET /services` endpoint.
// Each service maps to one or more product categories so the page can link
// straight back into the Shop with the right filter applied.
export const SERVICES = [
  {
    id: 'grain-transferring',
    title: 'Grain Transferring Solutions',
    icon: 'move-horizontal',
    image: 'assets/products/pipe-mounted-1.jpeg',
    tagline: 'Move grain fast, over long distances, with far less manual handling.',
    description: 'We supply and support flexible, motor-driven grain transferring systems that move rice, wheat, corn, soybean and powders between trucks, stores and processing points — sized to fit daily farm and mill use.',
    benefits: [
      'Transfer capacity up to 18 tons/hour',
      'Pipe lengths from 30 ft to 500 ft',
      'Motor options from 5 HP to 16 HP',
      'Cuts down manual loading and labour time',
    ],
    process: [
      'Share your site layout and daily grain volume with our team',
      'We recommend a pipe length and motor configuration',
      'Get a purchase code and confirm delivery details',
      'On-site setup guidance provided on request',
    ],
    categoryId: 'transferring',
  },
  {
    id: 'grain-collecting',
    title: 'Grain Collecting & Field Recovery',
    icon: 'circle-dot',
    image: 'assets/products/collector-field.jpeg',
    tagline: 'Recover loose grain from threshing floors and open yards efficiently.',
    description: 'Track-mounted and wheeled collectors gather loose grain from the ground and feed it into an inclined elevator, cutting manual scooping and speeding up cleanup after threshing.',
    benefits: [
      'Handles rice, corn, wheat, soybean and side crops',
      'Adjustable-incline elevator',
      'Stable movement across loose grain heaps',
      'Faster yard and threshing-floor cleanup after harvest',
    ],
    process: [
      'Tell us your terrain and typical heap size',
      'We match a collector unit to your operation',
      'Purchase code and delivery are arranged',
      'Live demonstration available on request',
    ],
    categoryId: 'collecting',
  },
  {
    id: 'grain-bagging',
    title: 'Grain Bagging & Packaging',
    icon: 'package',
    image: 'assets/products/collector-bags.jpeg',
    tagline: 'Consistent, fast bag-filling for grains and powders.',
    description: 'Bagging attachments and collecting-and-bagging machines pair with your existing setup for consistent fill weight and quick bag changeovers, so filled bags are ready to stack and move.',
    benefits: [
      'Up to 90 bags/hour',
      'Standard 50 kg woven bag compatibility',
      'Consistent fill weight across bags',
      'Pairs with any Farm Craft collector unit',
    ],
    process: [
      'Confirm your bag size and target throughput',
      'We recommend the right bagging attachment',
      'Get a purchase code and delivery schedule',
      'Optional on-site setup walkthrough',
    ],
    categoryId: 'bagging',
  },
  {
    id: 'custom-configuration',
    title: 'Custom Machinery Configuration',
    icon: 'settings-2',
    image: 'assets/products/collector-diagram.jpeg',
    tagline: 'Motor, pipe and mounting options matched to your operation, not the other way around.',
    description: 'Every farm, mill and store is different. We help you choose motor output, pipe length, mounting style and accessories so the machinery fits your daily volume and available space.',
    benefits: [
      'Configurations from 5 HP to 16 HP motors',
      'Fixed, wheeled or track-mounted builds',
      'Sized to your grain type and daily volume',
      'One point of contact for the full setup',
    ],
    process: [
      'Describe your operation — grain type, volume, space',
      'We propose one or two configurations to compare',
      'Choose a configuration inside the Get a Code flow',
      'Confirm your order and track it under My Orders',
    ],
    categoryId: 'machinery',
  },
  {
    id: 'installation-support',
    title: 'On-Site Installation & Setup Guidance',
    icon: 'wrench',
    image: 'assets/products/pipe-frame.jpeg',
    tagline: 'Get your machinery running correctly from day one.',
    description: 'Once your order is confirmed, our team can walk you through safe setup, pipe routing and first-run checks so your machine is working correctly from the very start.',
    benefits: [
      'Guided first-time setup',
      'Safety and operating checks',
      'Pipe routing and mounting guidance',
      'Fewer early breakdowns caused by incorrect setup',
    ],
    process: [
      'Confirm delivery and your preferred setup date',
      'Our team shares a simple setup checklist',
      'Guided walkthrough, in person or by phone',
      'Sign-off once the machine is running smoothly',
    ],
    categoryId: 'handling',
  },
  {
    id: 'after-sales-support',
    title: 'After-Sales Support & Maintenance',
    icon: 'headphones',
    image: 'assets/products/pipe-coil-2.jpeg',
    tagline: 'We stay reachable after the sale, not just before it.',
    description: 'From spare pipe sections to troubleshooting help, our team supports Farm Craft machinery for the long run — reach out any time using your order ID or purchase code.',
    benefits: [
      'Spare parts and pipe sections available',
      'Troubleshooting support by phone or WhatsApp',
      'Guidance on routine maintenance',
      'Support tied directly to your order and purchase code',
    ],
    process: [
      'Reach out with your purchase code or order ID',
      'Describe the issue or the part you need',
      'Our team advises the next steps',
      'We follow up with you until it is resolved',
    ],
    categoryId: 'accessories',
  },
];

export const DEMO_CUSTOMER = {
  email: 'customer@farmcraft.com',
  password: 'customer123',
  name: 'Ravi Kumar',
  mobile: '+91 98765 43210',
};
